# Generated by Django 4.2.6 on 2023-10-22 13:15

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLearningModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('batch_size', models.DecimalField(decimal_places=0, max_digits=4)),
                ('epochs', models.CharField(choices=[('25', 25), ('50', 50)], max_length=4)),
                ('learning_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('optimizer', models.CharField(max_length=10)),
                ('dataset', models.CharField(max_length=255)),
                ('accuracy_graph', models.ImageField(null=True, upload_to=core.models.graph_accuracy_image_file_path)),
                ('loss_graph', models.ImageField(null=True, upload_to=core.models.graph_loss_image_file_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
