# Generated by Django 4.2.6 on 2023-10-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlearningmodel',
            name='batch_size',
            field=models.CharField(choices=[('16', '16'), ('32', '32'), ('64', '64'), ('128', '128')], max_length=4),
        ),
        migrations.AlterField(
            model_name='transferlearningmodel',
            name='dataset',
            field=models.CharField(choices=[('Smote+Original+Image Processing', 'Smote+Original+Image Processing'), ('Original+Image Processing', 'Original+Image Processing'), ('Augmentation+Original+Image Processing', 'Augmentation+Original+Image Processing')], max_length=255),
        ),
        migrations.AlterField(
            model_name='transferlearningmodel',
            name='learning_rate',
            field=models.CharField(choices=[('0.001', '0.001'), ('0.005', '0.005')], max_length=6),
        ),
        migrations.AlterField(
            model_name='transferlearningmodel',
            name='optimizer',
            field=models.CharField(choices=[('Adam', 'Adam'), ('Adamax', 'Adamax'), ('RMSprop', 'RMSprop')], max_length=10),
        ),
    ]
