# Generated by Django 3.2.22 on 2023-10-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231026_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlearningmodel',
            name='dropout',
            field=models.CharField(choices=[('0.2', '0.2'), ('0.3', '0.3'), ('0.4', '0.4'), ('0.5', '0.5')], default='0.2', max_length=5),
        ),
    ]
