# Generated by Django 3.2.22 on 2023-10-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transferlearningmodel_dropout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlearningmodel',
            name='dropout',
            field=models.CharField(blank=True, choices=[('0.2', '0.2'), ('0.3', '0.3'), ('0.4', '0.4'), ('0.5', '0.5')], default='0.2', max_length=5),
        ),
    ]
