# Generated by Django 3.2.22 on 2023-10-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transferlearningmodel_dropout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlearningmodel',
            name='dropout',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
