# Generated by Django 4.2.7 on 2023-11-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_capstonedata_delete_transferlearningmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capstonedata',
            options={'verbose_name_plural': 'CapstoneData'},
        ),
        migrations.AlterField(
            model_name='capstonedata',
            name='dataset',
            field=models.CharField(choices=[('Original+Smote+Image Processing', 'Original+Smote+Image Processing'), ('Original+Image Processing', 'Original+Image Processing'), ('Original+Augmentation+Image Processing', 'Original+Augmentation+Image Processing')], default='Original+Image Processing', max_length=255),
        ),
        migrations.AlterField(
            model_name='capstonedata',
            name='dropout',
            field=models.CharField(blank=True, choices=[('0.2', '0.2'), ('0.3', '0.3'), ('0.4', '0.4'), ('0.5', '0.5')], max_length=5),
        ),
    ]
