# Generated by Django 4.2.6 on 2023-10-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transferlearningmodel_batch_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferlearningmodel',
            name='testing_accuracy',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='transferlearningmodel',
            name='training_accuracy',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='transferlearningmodel',
            name='validation_accuracy',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
