# Generated by Django 3.2.22 on 2023-10-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transferlearningmodel_testing_accuracy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferlearningmodel',
            name='user',
        ),
    ]
