# Generated by Django 3.2.22 on 2023-10-31 10:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_transferlearningmodel_dropout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferlearningmodel',
            name='accuracy_graph',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.graph_accuracy_image_file_path),
        ),
        migrations.AlterField(
            model_name='transferlearningmodel',
            name='loss_graph',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.graph_loss_image_file_path),
        ),
    ]
